"""initial

Revision ID: 1df64c5ad249
Revises: 749c7fe9b284
Create Date: 2023-03-03 23:58:37.199176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df64c5ad249'
down_revision = '749c7fe9b284'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions_action', sa.Column('has_permission', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions_action', 'has_permission')
    # ### end Alembic commands ###
