"""initial

Revision ID: cb6b16198dad
Revises: efee73ab5d0b
Create Date: 2023-01-24 16:30:37.376958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6b16198dad'
down_revision = 'efee73ab5d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), server_default=sa.FetchedValue(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), server_default=sa.FetchedValue(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), server_default=sa.FetchedValue(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'deleted_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    # ### end Alembic commands ###
