"""initial

Revision ID: efee73ab5d0b
Revises: 73f43f6aa257
Create Date: 2023-01-24 16:27:43.538582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efee73ab5d0b'
down_revision = '73f43f6aa257'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
